import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "../app/component/AuthProvider/AuthProvider.jsx";
import { SessionProvider } from "next-auth/react";
import { EmailProvider } from "../context/Emailcontext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          {" "}
          <EmailProvider>
            <AuthProvider>{children}</AuthProvider>
          </EmailProvider>{" "}
        </SessionProvider>
      </body>
    </html>
  );
}
